name: cs7642
channels:
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - openssl=1.0.2p=h1de35cc_0
  - pip=9.0.1=py34_1
  - python=3.4.5=0
  - readline=6.2=2
  - setuptools=27.2.0=py34_0
  - sqlite=3.13.0=0
  - tk=8.5.18=0
  - wheel=0.29.0=py34_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=hf3cbc9b_2
prefix: /Users/ykxy006/miniconda3/envs/cs7642

